// utils/options.ts
export const options = [
    // Development
    { value: "backend-development", label: "Backend Development" },
    { value: "frontend-development", label: "Frontend Development" },
    { value: "full-stack-development", label: "Full Stack Development" },
    { value: "web-development", label: "Web Development" },
    { value: "mobile-app-development", label: "Mobile App Development" },
    { value: "game-development", label: "Game Development" },
    { value: "blockchain-development", label: "Blockchain Development" },
    { value: "e-commerce-development", label: "E-commerce Development" },
    { value: "cloud-computing", label: "Cloud Computing" },
    { value: "data-engineering", label: "Data Engineering" },
    { value: "data-science", label: "Data Science" },
    { value: "machine-learning", label: "Machine Learning" },
    { value: "artificial-intelligence", label: "Artificial Intelligence" },
    { value: "natural-language-processing", label: "Natural Language Processing (NLP)" },
    { value: "computer-vision", label: "Computer Vision" },
    { value: "ar-vr-development", label: "AR/VR Development" },
    { value: "devops", label: "DevOps" },
    { value: "software-testing-qa", label: "Software Testing/QA" },
    { value: "embedded-systems", label: "Embedded Systems" },
    { value: "robotics", label: "Robotics" },
    { value: "database-administration", label: "Database Administration" },
    { value: "network-administration", label: "Network Administration" },
    { value: "api-development", label: "API Development" },
    { value: "scripting", label: "Scripting" },
    { value: "cybersecurity", label: "Cybersecurity" },
    { value: "ethical-hacking", label: "Ethical Hacking" },
    { value: "quantum-computing", label: "Quantum Computing" },
    { value: "game-design", label: "Game Design" },
    { value: "virtualization", label: "Virtualization" },
    { value: "internet-of-things", label: "Internet of Things (IoT)" },
    { value: "software-architecture", label: "Software Architecture" },
    { value: "code-refactoring", label: "Code Refactoring" },
    { value: "data-visualization", label: "Data Visualization" },
  
    // Design
    { value: "ui-ux-design", label: "UI/UX Design" },
    { value: "graphic-design", label: "Graphic Design" },
    { value: "interaction-design", label: "Interaction Design" },
    { value: "industrial-design", label: "Industrial Design" },
    { value: "animation", label: "Animation" },
    { value: "3d-modeling", label: "3D Modeling" },
    { value: "motion-design", label: "Motion Design" },
    { value: "typography", label: "Typography" },
    { value: "branding", label: "Branding" },
    { value: "illustration", label: "Illustration" },
  
    // Marketing and Business
    { value: "digital-marketing", label: "Digital Marketing" },
    { value: "content-marketing", label: "Content Marketing" },
    { value: "seo", label: "SEO (Search Engine Optimization)" },
    { value: "email-marketing", label: "Email Marketing" },
    { value: "social-media-management", label: "Social Media Management" },
    { value: "affiliate-marketing", label: "Affiliate Marketing" },
    { value: "advertising", label: "Advertising" },
    { value: "sales", label: "Sales" },
    { value: "market-research", label: "Market Research" },
    { value: "product-management", label: "Product Management" },
    { value: "project-management", label: "Project Management" },
    { value: "customer-relationship-management", label: "Customer Relationship Management (CRM)" },
    { value: "business-analysis", label: "Business Analysis" },
    { value: "finance-management", label: "Finance Management" },
    { value: "financial-analysis", label: "Financial Analysis" },
    { value: "supply-chain-management", label: "Supply Chain Management" },
    { value: "operations-management", label: "Operations Management" },
    { value: "human-resources", label: "Human Resources" },
    { value: "recruitment", label: "Recruitment" },
  
    // Writing and Content Creation
    { value: "technical-writing", label: "Technical Writing" },
    { value: "copywriting", label: "Copywriting" },
    { value: "content-creation", label: "Content Creation" },
    { value: "editing", label: "Editing" },
    { value: "proofreading", label: "Proofreading" },
    { value: "screenwriting", label: "Screenwriting" },
    { value: "blogging", label: "Blogging" },
  
    // Engineering
    { value: "civil-engineering", label: "Civil Engineering" },
    { value: "mechanical-engineering", label: "Mechanical Engineering" },
    { value: "electrical-engineering", label: "Electrical Engineering" },
    { value: "environmental-engineering", label: "Environmental Engineering" },
    { value: "biomedical-engineering", label: "Biomedical Engineering" },
    { value: "chemical-engineering", label: "Chemical Engineering" },
    { value: "aerospace-engineering", label: "Aerospace Engineering" },
  
    // Healthcare and Life Sciences
    { value: "bioinformatics", label: "Bioinformatics" },
    { value: "clinical-research", label: "Clinical Research" },
    { value: "medical-writing", label: "Medical Writing" },
    { value: "pharmacology", label: "Pharmacology" },
  
    // Others
    { value: "music-production", label: "Music Production" },
    { value: "video-editing", label: "Video Editing" },
    { value: "photography", label: "Photography" },
    { value: "event-management", label: "Event Management" },
    { value: "agriculture-technology", label: "Agriculture Technology" },
    { value: "urban-planning", label: "Urban Planning" },
    { value: "architecture", label: "Architecture" },
    { value: "renewable-energy", label: "Renewable Energy" },
    { value: "technical-support", label: "Technical Support" },
    { value: "customer-support", label: "Customer Support" },
    { value: "it-support", label: "IT Support" },
    { value: "legal-compliance", label: "Legal Compliance" },
    { value: "cryptocurrency-trading", label: "Cryptocurrency Trading" },
    { value: "stock-trading", label: "Stock Trading" },
    { value: "quantitative-research", label: "Quantitative Research" },
    { value: "data-analysis", label: "Data Analysis" },
    { value: "data-entry", label: "Data Entry" },
    { value: "quality-assurance", label: "Quality Assurance (QA)" },
    { value: "performance-testing", label: "Performance Testing" },
    { value: "game-testing", label: "Game Testing" },
    { value: "security-testing", label: "Security Testing" },
    { value: "penetration-testing", label: "Penetration Testing" },
    { value: "load-testing", label: "Load Testing" },
  ];
  